### PR TITLE
Avro schema replication shouldn't fail with HA configured

### LINKED ISSUE #69: Avro schema is not found from SerdeProperties avro.schema.url when replicating from Hadoop configured for  HA

### PR DESCRIPTION
**Pull request by courtsVII**
fixes #69

### CODE REVIEW

File: circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/SchemaCopier.java [hunk 1]
```diff
@@ -52,17 +64,102 @@ public Path copy(String source, String destination) {
...
+    String destinationNameService = replicaHiveConf.get(NAMESERVICES_PARAMETER);
+    Path destinationLocation = locationWithNameService(new Path(destination, fileName(source)).toString(),
+        destinationNameService);
     copyToRemote(localLocation, destinationLocation);
 
     LOG.info("Avro schema has been copied from '{}' to '{}'", source, destinationLocation);
     return destinationLocation;
   }
 
+  private void tryCopyToLocal(String source, Path localLocation) {
```
[the remark this answers is not in the document]
Comment (courtsVII) [reply circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/SchemaCopier.java]: I agree with all the above, still in WIP stages so will improve

**Comment by massdosage** [comment]
So, when we need to configure the copiers to deal with this situation we do something like
```
source-catalog:
...
configuration-properties:
dfs.nameservices: foo-ha
dfs.client.failover.proxy.provider.foo-ha: org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider
dfs.ha.namenodes.foo-ha: nn1,nn2
dfs.namenode.rpc-address.foo-ha.nn1: nn1host:8020
dfs.namenode.rpc-address.foo-ha.nn2: nn2host:8020
```
If they are running into this issue this means they are running against HDFS with a HA NN and would already have something like this in their config, Can't we just hand this config over to however we create the FileSystem? I assume the copiers must be using the above values to resolve file locations on HDFS so we should be able to do it the same way to resolve the Avro schema file locations.

File: circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/SchemaCopier.java [hunk 2]
```diff
@@ -75,12 +75,14 @@ public Path copy(String source, String destination) {
   }
 
   private void copyToLocal(Path sourceLocation, Path localLocation) {
-    FileSystem sourceFileSystem;
     try {
+      LOG.info("Attempting to copy from {} to {}", sourceLocation, localLocation);
+      FileSystem sourceFileSystem;
```
Comment (patduin) [inline circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/SchemaCopier.java]: I guess you can combine the this and the next line

File: circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/SchemaCopier.java [hunk 3]
```diff
@@ -13,35 +13,34 @@
...
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Component;
 
-import com.hotels.bdp.circustrain.api.CircusTrainException;
+import java.io.IOException;
+import java.nio.file.Files;
+
+import static com.google.common.base.Preconditions.checkNotNull;
```
Comment (massdosage) [inline circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/SchemaCopier.java]: Your imports don't match our standard import ordering, statics need to come first etc. Please review and make sure they line up with what's documented on our "London standards" page. Nothing should change here other than what you've added.

File: circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/NameServicePathResolver.java [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+
+import org.apache.hadoop.conf.Configuration;
+import org.apache.hadoop.fs.Path;
+import org.apache.hadoop.hdfs.DFSConfigKeys;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+import java.net.URI;
+
+import static org.apache.commons.lang.StringUtils.isBlank;
```
Comment (massdosage) [inline circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/NameServicePathResolver.java]: Static import in the wrong place (need to come first according to our convention)

File: circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/SchemaCopier.java (hunk 2 above)
Comment (massdosage) [reply circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/SchemaCopier.java]: +1

File: circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/SchemaCopier.java [hunk 5]
```diff
@@ -75,12 +75,14 @@ public Path copy(String source, String destination) {
...
-    FileSystem sourceFileSystem;
     try {
+      LOG.info("Attempting to copy from {} to {}", sourceLocation, localLocation);
+      FileSystem sourceFileSystem;
       sourceFileSystem = sourceLocation.getFileSystem(sourceHiveConf);
       sourceFileSystem.copyToLocalFile(false, sourceLocation, localLocation);
-    } catch (IOException e) {
-      throw new CircusTrainException("Couldn't copy file from " + sourceLocation + " to" + localLocation, e);
+      LOG.info("Copy from {} to {} succeeded", sourceLocation, localLocation);
+    } catch (Exception e) {
```
Comment (massdosage) [inline circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/SchemaCopier.java]: Why has this changed to Exception instead of IOE?

File: circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/NameServicePathResolver.java [hunk 6]
```diff
@@ -0,0 +1,57 @@
...
+  private static final Logger LOG = LoggerFactory.getLogger(NameServicePathResolver.class);
+
+  private final Configuration configuration;
+
+  public NameServicePathResolver(Configuration configuration) {
+    this.configuration = configuration;
+  }
+
+  public Path resolve(String url) {
+    String nameService = configuration.get(DFSConfigKeys.DFS_NAMESERVICES);
```
Comment (massdosage) [inline circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/NameServicePathResolver.java]: Is this something we need to document? i.e. how you set this up and when it's used?

Comment (courtsVII) [reply circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/NameServicePathResolver.java]: I'm not sure, Hadoop docs cover it quite well, and the users that reported the issue were already aware of the configuration

Comment (massdosage) [reply circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/NameServicePathResolver.java]: OK, so is this something they've set already in one of the Hadoop config files that is on the classpath? i.e. it's not something they set in Circus Train config anywhere?

Comment (courtsVII) [reply circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/NameServicePathResolver.java]: No only `dfs.nameservices`

Comment (courtsVII) [reply circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/NameServicePathResolver.java]: I think this is the minimum config required for copy to succeed

`source-catalog:
...
configuration-properties:
dfs.nameservices: foo-ha
dfs.client.failover.proxy.provider.foo-ha: org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider
dfs.ha.namenodes.foo-ha: nn1,nn2
dfs.namenode.rpc-address.foo-ha.nn1: nn1host:8020
dfs.namenode.rpc-address.foo-ha.nn2: nn2host:8020`

but circus-train-avro specifically only needs `dfs.nameservices`

**Comment by patduin** [comment]
Add line in the CHANGELOG and I am happy to approve

File: circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/SchemaCopier.java [hunk 7]
```diff
@@ -13,35 +13,33 @@
...
 package com.hotels.bdp.circustrain.avro.util;
 
 import static com.google.common.base.Preconditions.checkNotNull;
-
 import static com.hotels.bdp.circustrain.avro.util.AvroStringUtils.fileName;
 
 import java.io.IOException;
 import java.nio.file.Files;
-
+import org.apache.hadoop.conf.Configuration;
```
Comment (massdosage) [inline circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/SchemaCopier.java]: NABD but there should be a line break between java.* and org.* imports (like it was before)

File: circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/SchemaCopier.java [hunk 8]
```diff
@@ -75,12 +74,13 @@ public Path copy(String source, String destination) {
   }
 
   private void copyToLocal(Path sourceLocation, Path localLocation) {
-    FileSystem sourceFileSystem;
     try {
+      FileSystem sourceFileSystem;
```
Comment (massdosage) [inline circus-train-avro/src/main/java/com/hotels/bdp/circustrain/avro/util/SchemaCopier.java]: You could combine lines 78 and 79 into one.

File: circus-train-avro/src/test/java/com/hotels/bdp/circustrain/avro/util/NameServicePathResolverTest.java [hunk 9]
```diff
@@ -0,0 +1,93 @@
...
+ */
+
+package com.hotels.bdp.circustrain.avro.util;
+
+import org.apache.hadoop.conf.Configuration;
+import org.apache.hadoop.fs.Path;
+import org.apache.hadoop.hdfs.DFSConfigKeys;
+import org.junit.Test;
+
+import static org.junit.Assert.assertEquals;
```
Comment (massdosage) [inline circus-train-avro/src/test/java/com/hotels/bdp/circustrain/avro/util/NameServicePathResolverTest.java]: Static imports go first.
