### PR TITLE
Reset partition parameters for SnsListener

### LINKED ISSUE #104: SNS listener doesn't clear partitioned state correctly
When running two replications: one partitioned and one unpartitioned. 
See the: `com.hotels.bdp.circustrain.aws.sns.event.SnsListener`
The partitionKeys and modifiedPartitions are not cleared in between replications and will be incorrectly reported in sns messages for both replications.

### PR DESCRIPTION
**Pull request by AnanaMJ**
Fixes #104

### CODE REVIEW

File: circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java [hunk 1]
```diff
@@ -118,29 +118,44 @@ public void tableReplicationStart(EventTableReplication tableReplication, String
...
+      partitionKeyTypes = null;
+    }
   }
 
   @Override
   public void tableReplicationFailure(EventTableReplication tableReplication, String eventId, Throwable t) {
-    if (startTime == null) {
-      startTime = clock.getTime();
+    try {
+      if (startTime == null) {
```
Comment (massdosage) [inline circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java]: This code was already here but I wonder why we have this null check and change to `startTime` in `tableReplicationFailure` but not in `tableReplicationSuccess`? This makes me think though - should we also set `startTime` to null at the end of both of these methods?

File: circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java [hunk 2]
```diff
@@ -118,29 +118,44 @@ public void tableReplicationStart(EventTableReplication tableReplication, String
...
+      EventReplicaTable replicaTable = tableReplication.getReplicaTable();
+      SnsMessage message = new SnsMessage(SnsMessageType.FAILURE, config.getHeaders(), startTime, endTime, eventId,
+          sourceCatalog.getName(), replicaCatalog.getName(), replicaCatalog.getHiveMetastoreUris(),
+          tableReplication.getSourceTable().getQualifiedName(), tableReplication.getQualifiedReplicaName(),
+          replicaTable.getTableLocation(), partitionKeyTypes,
+          getModifiedPartitions(partitionsToAlter, partitionsToCreate), getBytesReplicated(), t.getMessage());
+      publish(config.getFailTopic(), message);
+    } finally {
+      // reset registered partitions between database cycles
+      partitionsToCreate = null;
```
Comment (massdosage) [inline circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java]: I don't think this is covered by any tests?

File: circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java [hunk 3]
```diff
@@ -118,29 +118,44 @@ public void tableReplicationStart(EventTableReplication tableReplication, String
...
+      String endTime = clock.getTime();
+      EventReplicaTable replicaTable = tableReplication.getReplicaTable();
+      SnsMessage message = new SnsMessage(SnsMessageType.SUCCESS, config.getHeaders(), startTime, endTime, eventId,
+          sourceCatalog.getName(), replicaCatalog.getName(), replicaCatalog.getHiveMetastoreUris(),
+          tableReplication.getSourceTable().getQualifiedName(), tableReplication.getQualifiedReplicaName(),
+          replicaTable.getTableLocation(), partitionKeyTypes,
+          getModifiedPartitions(partitionsToAlter, partitionsToCreate), getBytesReplicated(), null);
+      publish(config.getSuccessTopic(), message);
+    } finally {
+      // reset registered partitions between database cycles
```
[the remark this answers is not in the document]
Comment (AnanaMJ) [reply circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java]: Yep, all good points :) 
By having a function I won't need the comment so that's even better!

File: circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java [hunk 4]
```diff
@@ -118,29 +118,44 @@ public void tableReplicationStart(EventTableReplication tableReplication, String
...
+    }
   }
 
   @Override
   public void tableReplicationFailure(EventTableReplication tableReplication, String eventId, Throwable t) {
-    if (startTime == null) {
-      startTime = clock.getTime();
+    try {
+      if (startTime == null) {
+
```
[the remark this answers is not in the document]
Comment (AnanaMJ) [reply circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java]: Ah, when I added the `try`, Eclipse put the closing bracket on that line 😆
I removed it now

File: circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java (hunk 1 above)
Comment (AnanaMJ) [reply circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java]: Maybe because of the functions are used in `Locomotive.java`:
```java
try {
  Replication replication = replicationFactory.newInstance(tableReplication);
  tableReplicationListener.tableReplicationStart(...);
  tableReplicationListener.tableReplicationSuccess(...);
} catch (Throwable t) {
  replicationFailures++;
  completionCode = CompletionCode.FAILURE;
  LOG.error("Failed to replicate: {}.", summary, t);
  tableReplicationListener.tableReplicationFailure(...);
```

If there's an issue with creating a new instance, then `startTime` might not have been initialised, but if everything works fine, `tableReplicationSuccess` should have the startTime that was set in `tableReplicationStart`.

So maybe this is fine?

Comment (massdosage) [reply circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java]: Yeah, that makes sense. There's quite a lot of assumptions made in this class based on the order that things are called on it which isn't ideal but that's a different topic ;)

When the above failure happens is the listener ever called again? i.e. could the time get set in the failure, and it then tries to do something else which also fails, at which point the time in the failure would be the previous failure's start time?

File: circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java (hunk 2 above)
Comment (AnanaMJ) [reply circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java]: Done :)

File: circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java (hunk 1 above)
Comment (massdosage) [reply circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java]: Yes, I'm fine with leaving the assumptions on call order for another day. I just wonder if it's worth clearing the startTime though?

Comment (patduin) [reply circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java]: that's true, that's but in that case the whole start-end time is rather useless info anyway.
Pretty sure the null check is there to have a quick nullPointerException fix and have "some" value in the failure message.

Comment (patduin) [reply circus-train-aws-sns/src/main/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListener.java]: I mean by all means set startTime to null after a success, just in case. That won't hurt.

File: circus-train-aws-sns/src/test/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListenerTest.java [hunk 5]
```diff
@@ -322,4 +325,182 @@ public void messageSizeExceeded() throws Exception {
...
+            + "\"replicaTableLocation\":\""
+            + REPLICA_TABLE_LOCATION
+            + "\",\"replicaMetastoreUris\":\""
+            + REPLICA_METASTORE_URIS
+            + "\",\"bytesReplicated\":40}"));
+  }
+
+  @Test
+  public void noTableReplicationStartForConsecutiveReplications() {
+    SnsListener listener = new SnsListener(client, config, clock);
```
[the remark this answers is not in the document]
Comment (patduin) [reply circus-train-aws-sns/src/test/java/com/hotels/bdp/circustrain/aws/sns/event/SnsListenerTest.java]: this is what I meant with calling it twice, all good
