### PR TITLE
[issue-32] Add compatibility with Hive 1.2.x

### LINKED ISSUE #32: Error replicating from source cluster running Hive 1.2.1 to replica cluster running Hive 2.3.2
The following error occurs when running Circus Train on EMR with Hive 2.3.2 libraries performing a replication where the source is running Hive 1.2.1 and replica is running 2.3.2. The issue appears to be a Thrift backwards incompatability issue between a newer Hive client and an older Hive server. Here is an example failing log output (with certain host names redacted):

> Using /home/hadoop/circus-train-11.1.1-SNAPSHOT
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/usr/lib/hadoop/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/home/hadoop/circus-train-11.1.1-SNAPSHOT/lib/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
> 18/02/12 11:22:53 INFO circustrain.CircusTrain: Maven-ArtifactId=circus-train-core; Built-By=ddelcastilloperez; Build-DateTime=2018-02-12T11:20:19Z; Created-By=Apache Maven 3.5.2; Build-Jdk=1.8.0_152; Build-Version=11.1.1-SNAPSHOT; Manifest-Version=1.0; Maven-GroupId=com.hotels;
> 18/02/12 11:22:54 INFO util.Version: HV000001: Hibernate Validator 5.2.4.Final
>          ee@@@@@@@@@@@@@@@
>        e@@@@@@@@@@@@@@@
>       @@@"     .-.----.      ___ _                   ___ _                   _
>      @@"___   / o )    \    / __\ |__   ___   ___   / __\ |__   ___   ___   / \
>     II__[w]   || ´ __  |'  / /  | '_ \ / _ \ / _ \ / /  | '_ \ / _ \ / _ \ /  /
>    {======|_ '- |||  |||  / /___| | | | (_) | (_) / /___| | | | (_) | (_) /\_/
>   /oO--000'"`--OO----OO-' \____/|_| |_|\___/ \___/\____/|_| |_|\___/ \___/\/
> 18/02/12 11:22:54 INFO circustrain.CircusTrain: Starting CircusTrain on ip-10-29-171-135.us-west-2.compute.internal with PID 5196 (/home/hadoop/circus-train-11.1.1-SNAPSHOT/lib/circus-train-all-latest.jar started by hadoop in /home/hadoop)
> 18/02/12 11:22:54 INFO circustrain.CircusTrain: The following profiles are active: replication,housekeeping
> 18/02/12 11:22:54 INFO annotation.AnnotationConfigApplicationContext: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@fb5aeed: startup date [Mon Feb 12 11:22:54 UTC 2018]; root of context hierarchy
> 18/02/12 11:22:57 WARN annotation.ConfigurationClassEnhancer: @Bean method EnableEncryptablePropertySourcesConfiguration.enableEncryptablePropertySourcesPostProcessor is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.
> 18/02/12 11:22:57 INFO jasyptspringboot.EnableEncryptablePropertySourcesPostProcessor: Post-processing PropertySource instances
> 18/02/12 11:22:57 INFO jasyptspringboot.EnableEncryptablePropertySourcesPostProcessor: Converting PropertySource commandLineArgs[org.springframework.core.env.SimpleCommandLinePropertySource] to EncryptableEnumerablePropertySourceWrapper
> 18/02/12 11:22:57 INFO jasyptspringboot.EnableEncryptablePropertySourcesPostProcessor: Converting PropertySource systemProperties[org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
> 18/02/12 11:22:57 INFO jasyptspringboot.EnableEncryptablePropertySourcesPostProcessor: Converting PropertySource systemEnvironment[org.springframework.core.env.SystemEnvironmentPropertySource] to EncryptableMapPropertySourceWrapper
> 18/02/12 11:22:57 INFO jasyptspringboot.EnableEncryptablePropertySourcesPostProcessor: Converting PropertySource random[org.springframework.boot.context.config.RandomValuePropertySource] to EncryptablePropertySourceWrapper
> 18/02/12 11:22:57 INFO jasyptspringboot.EnableEncryptablePropertySourcesPostProcessor: Converting PropertySource applicationConfig: [file:/home/hadoop/BDP-1151.yml][org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
> 18/02/12 11:22:57 INFO jasyptspringboot.EnableEncryptablePropertySourcesPostProcessor: Converting PropertySource defaultProperties[org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
> 18/02/12 11:22:57 INFO annotation.AutowiredAnnotationBeanPostProcessor: JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
> 18/02/12 11:22:57 INFO support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker: Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [class org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$85b58278] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 18/02/12 11:22:57 INFO support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker: Bean 'bindS3AFileSystem' of type [class com.hotels.bdp.circustrain.aws.BindS3AFileSystem] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 18/02/12 11:22:57 INFO support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker: Bean 's3CredentialsUtils' of type [class com.hotels.bdp.circustrain.aws.S3CredentialsUtils] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 18/02/12 11:22:57 INFO support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker: Bean 'housekeepingConfiguration' of type [class com.hotels.housekeeping.HousekeepingConfiguration$$EnhancerBySpringCGLIB$$fd62bc27] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 18/02/12 11:22:58 INFO support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker: Bean 'stringToDurationConverter' of type [class com.hotels.housekeeping.converter.StringToDurationConverter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 18/02/12 11:22:58 INFO support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker: Bean 'GCPSecurity' of type [class com.hotels.bdp.circustrain.gcp.context.GCPSecurity$$EnhancerBySpringCGLIB$$3b0e0b7b] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 18/02/12 11:22:58 INFO hikari.HikariDataSource: HikariPool-1 - Starting...
> 18/02/12 11:22:59 INFO hikari.HikariDataSource: HikariPool-1 - Start completed.
> 18/02/12 11:22:59 INFO init.ScriptUtils: Executing SQL script from URL [jar:file:/home/hadoop/circus-train-11.1.1-SNAPSHOT/lib/circus-train-all-latest.jar!/schema.sql]
> 18/02/12 11:22:59 INFO init.ScriptUtils: Executed SQL script from URL [jar:file:/home/hadoop/circus-train-11.1.1-SNAPSHOT/lib/circus-train-all-latest.jar!/schema.sql] in 5 ms.
> 18/02/12 11:22:59 INFO init.ScriptUtils: Executing SQL script from URL [file:/tmp/hadoop-unjar5929440329897995965/schema.sql]
> 18/02/12 11:22:59 INFO init.ScriptUtils: Executed SQL script from URL [file:/tmp/hadoop-unjar5929440329897995965/schema.sql] in 0 ms.
> 18/02/12 11:22:59 INFO jpa.LocalContainerEntityManagerFactoryBean: Building JPA container EntityManagerFactory for persistence unit 'default'
> 18/02/12 11:22:59 INFO util.LogHelper: HHH000204: Processing PersistenceUnitInfo [
>     name: default
>     ...]
> 18/02/12 11:22:59 INFO hibernate.Version: HHH000412: Hibernate Core {4.3.11.Final}
> 18/02/12 11:22:59 INFO cfg.Environment: HHH000206: hibernate.properties not found
> 18/02/12 11:22:59 INFO cfg.Environment: HHH000021: Bytecode provider name : javassist
> 18/02/12 11:23:01 INFO common.Version: HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
> 18/02/12 11:23:01 INFO dialect.Dialect: HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
> 18/02/12 11:23:01 INFO ast.ASTQueryTranslatorFactory: HHH000397: Using ASTQueryTranslatorFactory
> 18/02/12 11:23:01 INFO hbm2ddl.SchemaUpdate: HHH000228: Running hbm2ddl schema update
> 18/02/12 11:23:01 INFO hbm2ddl.SchemaUpdate: HHH000102: Fetching database metadata
> 18/02/12 11:23:01 INFO hbm2ddl.SchemaUpdate: HHH000396: Updating schema
> 18/02/12 11:23:01 INFO hbm2ddl.TableMetadata: HHH000261: Table found: HOUSEKEEPING.CIRCUS_TRAIN.AUDIT_REVISION
> 18/02/12 11:23:01 INFO hbm2ddl.TableMetadata: HHH000037: Columns: [id, timestamp]
> 18/02/12 11:23:01 INFO hbm2ddl.TableMetadata: HHH000108: Foreign keys: []
> 18/02/12 11:23:01 INFO hbm2ddl.TableMetadata: HHH000126: Indexes: [primary_key_5]
> 18/02/12 11:23:01 INFO hbm2ddl.TableMetadata: HHH000261: Table found: HOUSEKEEPING.CIRCUS_TRAIN.LEGACY_REPLICA_PATH
> 18/02/12 11:23:01 INFO hbm2ddl.TableMetadata: HHH000037: Columns: [path, event_id, creation_timestamp, path_event_id, id]
> 18/02/12 11:23:01 INFO hbm2ddl.TableMetadata: HHH000108: Foreign keys: []
> 18/02/12 11:23:01 INFO hbm2ddl.TableMetadata: HHH000126: Indexes: [primary_key_1, uk_tlauv1txmi2vux3fqp1y1ueav_index_1]
> 18/02/12 11:23:01 INFO hbm2ddl.SchemaUpdate: HHH000232: Schema update complete
> 18/02/12 11:23:01 INFO circustrain.CircusTrain: Maven-ArtifactId=circus-train-core; Built-By=ddelcastilloperez; Build-DateTime=2018-02-12T11:20:19Z; Created-By=Apache Maven 3.5.2; Build-Jdk=1.8.0_152; Build-Version=11.1.1-SNAPSHOT; Manifest-Version=1.0; Maven-GroupId=com.hotels;
> 18/02/12 11:23:02 INFO context.CommonBeans: No Hadoop site XML is defined for catalog karmalab-dev.
> 18/02/12 11:23:02 INFO conf.HiveConf: Found configuration file file:/etc/hive/conf.dist/hive-site.xml
> 18/02/12 11:23:02 INFO context.CommonBeans: No Hadoop site XML is defined for catalog aws-data-lab.
> 18/02/12 11:23:03 WARN impl.FileSystemHousekeepingService: class com.hotels.housekeeping.service.impl.FileSystemHousekeepingService.fixIncompleteRecord(LegacyReplicaPath) should be removed in future.
> 18/02/12 11:23:04 INFO annotation.AnnotationMBeanExporter: Registering beans for JMX exposure on startup
> 18/02/12 11:23:04 INFO annotation.AnnotationMBeanExporter: Bean with name 'housekeepingDataSource' has been autodetected for JMX exposure
> 18/02/12 11:23:04 INFO annotation.AnnotationMBeanExporter: Located MBean 'housekeepingDataSource': registering with JMX server as MBean [com.zaxxer.hikari:name=housekeepingDataSource,type=HikariDataSource]
> 18/02/12 11:23:04 INFO core.Locomotive: 1 tables to replicate.
> 18/02/12 11:23:04 INFO core.Locomotive: Replicating karmalab-dev:ddelcastilloperez.access_log to aws-data-lab:bdp.access_log_dev replication mode 'FULL'.
> 18/02/12 11:23:04 INFO hive.metastore: Trying to connect to metastore with URI thrift://cheledwhdd004.karmalab.net:9083
> 18/02/12 11:23:04 INFO hive.metastore: Opened a connection to metastore, current connections: 1
> 18/02/12 11:23:04 INFO hive.metastore: Connected to metastore.
> 18/02/12 11:23:04 INFO hive.metastore: Closed a connection to metastore, current connections: 0
> 18/02/12 11:23:04 INFO hive.metastore: Trying to connect to metastore with URI thrift://replica:9083
> 18/02/12 11:23:04 INFO hive.metastore: Opened a connection to metastore, current connections: 1
> 18/02/12 11:23:04 INFO hive.metastore: Connected to metastore.
> 18/02/12 11:23:04 INFO hive.metastore: Closed a connection to metastore, current connections: 0
> 18/02/12 11:23:04 INFO source.Source: Retrieving table metadata for 'ddelcastilloperez.access_log'
> 18/02/12 11:23:04 INFO hive.metastore: Trying to connect to metastore with URI thrift://cheledwhdd004.karmalab.net:9083
> 18/02/12 11:23:04 INFO hive.metastore: Opened a connection to metastore, current connections: 1
> 18/02/12 11:23:05 INFO hive.metastore: Connected to metastore.
> 18/02/12 11:23:05 INFO hive.metastore: Closed a connection to metastore, current connections: 0
> 18/02/12 11:23:05 ERROR core.Locomotive: Failed to replicate: karmalab-dev:ddelcastilloperez.access_log to aws-data-lab:bdp.access_log_dev.
> com.hotels.bdp.circustrain.api.metastore.MetaStoreClientException: Cannot fetch table metadata for 'ddelcastilloperez.access_log'
>     at com.hotels.bdp.circustrain.core.HiveEndpoint.getTableAndStatistics(HiveEndpoint.java:132)
>     at com.hotels.bdp.circustrain.core.source.Source.getTableAndStatistics(Source.java:111)
>     at com.hotels.bdp.circustrain.core.ReplicationFactoryImpl.validate(ReplicationFactoryImpl.java:170)
>     at com.hotels.bdp.circustrain.core.ReplicationFactoryImpl.newInstance(ReplicationFactoryImpl.java:85)
>     at com.hotels.bdp.circustrain.core.Locomotive.run(Locomotive.java:111)
>     at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
>     at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781)
>     at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771)
>     at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
>     at com.hotels.bdp.circustrain.CircusTrain.main(CircusTrain.java:97)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
>     at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
> Caused by: org.apache.thrift.TApplicationException: Invalid method name: 'get_table_req'
>     at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
>     at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
>     at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table_req(ThriftHiveMetastore.java:1563)
>     at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_table_req(ThriftHiveMetastore.java:1550)
>     at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getTable(HiveMetaStoreClient.java:1344)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:169)
>     at com.sun.proxy.$Proxy91.getTable(Unknown Source)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at com.hotels.bdp.circustrain.api.metastore.CloseableMetaStoreClientFactory$CloseableMetaStoreClientInvocationHandler.invoke(CloseableMetaStoreClientFactory.java:47)
>     at com.sun.proxy.$Proxy92.getTable(Unknown Source)
>     at com.hotels.bdp.circustrain.core.HiveEndpoint.getTableAndStatistics(HiveEndpoint.java:114)
>     ... 15 more
> 18/02/12 11:23:05 INFO metrics.MetricSender: bdp.access_log_dev.replication_time : -1
> 18/02/12 11:23:05 INFO metrics.MetricSender: bdp.access_log_dev.completion_code : -1
> 18/02/12 11:23:05 INFO metrics.MetricSender: bdp.access_log_dev.bytes_replicated : 0
> 18/02/12 11:23:05 ERROR event.LoggingListener:REPLICATION_EVENTS: [event-id-unavailable] Failed to replicate 'karmalab-dev:ddelcastilloperez.access_log' to 'aws-data-lab:bdp.access_log_dev' with error 'Cannot fetch table metadata for 'ddelcastilloperez.access_log''
> 18/02/12 11:23:05 INFO metrics.MetricSender: tables_replicated : 1
> 18/02/12 11:23:05 INFO metrics.MetricSender: completion_code : -1
> 18/02/12 11:23:05 INFO housekeeping.HousekeepingRunner: Housekeeping at instant 2018-02-09T11:23:05.103Z has started
> 18/02/12 11:23:05 INFO housekeeping.HousekeepingRunner: Housekeeping at instant 2018-02-09T11:23:05.103Z has finished
> 18/02/12 11:23:05 INFO metrics.MetricSender: housekeeping : 1
> 18/02/12 11:23:05 INFO circustrain.CircusTrain: Started CircusTrain in 11.598 seconds (JVM running for 13.477)
> 18/02/12 11:23:05 INFO annotation.AnnotationConfigApplicationContext: Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@fb5aeed: startup date [Mon Feb 12 11:22:54 UTC 2018]; root of context hierarchy
> 18/02/12 11:23:05 INFO annotation.AnnotationMBeanExporter: Unregistering JMX-exposed beans on shutdown
> 18/02/12 11:23:05 INFO annotation.AnnotationMBeanExporter: Unregistering JMX-exposed beans
> 18/02/12 11:23:05 INFO jpa.LocalContainerEntityManagerFactoryBean: Closing JPA EntityManagerFactory for persistence unit 'default'
> 18/02/12 11:23:05 INFO hikari.HikariDataSource: HikariPool-1 - Shutdown initiated...
> 18/02/12 11:23:05 INFO pool.HikariPool: HikariPool-1 - Close initiated...
> 18/02/12 11:23:05 INFO pool.HikariPool: HikariPool-1 - Closed.
> 18/02/12 11:23:05 INFO hikari.HikariDataSource: HikariPool-1 - Shutdown completed.

### PR DESCRIPTION
**Pull request by ddcprg**
Fixes #32 

This is hack to work around the missing method when the client is 2.1 and the server is 1.2

### CODE REVIEW

**Comment by ddcprg** [comment]
I'll try to push the CC back to 75%

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+  private final TServiceClient tServiceClient;
+
+  public HiveMetaStoreClientCompatibility12x(IMetaStoreClient client) {
+    while (Proxy.isProxyClass(client.getClass())) {
+      InvocationHandler handler = Proxy.getInvocationHandler(client);
+      if (handler.getClass().isAssignableFrom(RetryingMetaStoreClient.class)) {
+        client = getField(handler, "base");
+        continue;
+      }
+      // TODO add CloseableMetaStoreClientInvocationHandler ?
```
Comment (massdosage) [inline circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java]: Do you still want to do this?

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+      if (field.isAccessible()) {
+        result = (T) field.get(object);
+      } else {
+        field.setAccessible(true);
+        result = (T) field.get(object);
+        field.setAccessible(false);
+      }
+      return result;
+    } catch (Exception e) {
+      throw new RuntimeException("Unable to hack client", e);
```
Comment (massdosage) [inline circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java]: Bonus points for amusing exception message

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java [hunk 3]
```diff
@@ -0,0 +1,128 @@
...
+        client = getField(handler, "base");
+        continue;
+      }
+      // TODO add CloseableMetaStoreClientInvocationHandler ?
+      throw new RuntimeException("Unknown InvocationHandler " + handler.getClass());
+    }
+    tServiceClient = getField(client, "client");
+  }
+
+  private static <T> T getField(Object object, String fieldName) {
```
Comment (massdosage) [inline circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java]: Does this need to be static?

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java [hunk 4]
```diff
@@ -0,0 +1,128 @@
...
+        result = (T) field.get(object);
+        field.setAccessible(false);
+      }
+      return result;
+    } catch (Exception e) {
+      throw new RuntimeException("Unable to hack client", e);
+    }
+  }
+
+  private static Table deepCopy(Table table) {
```
Comment (massdosage) [inline circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java]: This is only used once and is only one line, is it even worth having as a separate method? (and it's static while I don't think it needs to be)

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/CloseableMetaStoreClientFactory.java [hunk 5]
```diff
@@ -36,20 +42,48 @@ public static CloseableMetaStoreClient newInstance(IMetaStoreClient delegate) {
...
       }
     }
 
+    private Object invokeCompatibility(Method method, Object[] args) throws Throwable {
+      Class<?>[] argTypes = getTypes(args);
+      Method compatibilityMethod = compatibility.getClass().getMethod(method.getName(), argTypes);
+      return compatibilityMethod.invoke(compatibility, args);
+    }
+
+    private static Class<?>[] getTypes(Object[] args) {
```
Comment (massdosage) [inline circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/CloseableMetaStoreClientFactory.java]: Where does this code come from? Some third party library right? If so we should reference it here, update the license header above and also add this class to the list of files which the license plugin doesn't automatically update.

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java (hunk 3 above)
Comment (massdosage) [reply circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java]: Similar to my comment above, where does this code come from etc.

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java [hunk 6]
```diff
@@ -0,0 +1,128 @@
...
+    return table.deepCopy();
+  }
+
+  private void sendBase(String methodName, TBase<?, ?> args) throws TException {
```
Comment (massdosage) [inline circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java]: Do sendBase() and receiveBase() come from somewhere else? If so, the same as my other 2 comments above apply here.

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java [hunk 7]
```diff
@@ -0,0 +1,128 @@
...
+  public Table getTable(String dbname, String name) throws MetaException, TException, NoSuchObjectException {
+    return deepCopy(get_table(dbname, name));
+  }
+
+  private Table get_table(String dbname, String tbl_name) throws MetaException, NoSuchObjectException, TException {
+    send_get_table(dbname, tbl_name);
+    return recv_get_table();
+  }
+
+  private void send_get_table(String dbname, String tbl_name) throws TException {
```
Comment (massdosage) [inline circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java]: Or is this and the method below the ones that have been copied from Hive?

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java (hunk 1 above)
Comment (ddcprg) [reply circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java]: No, I'll add just a comment

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java (hunk 2 above)
Comment (ddcprg) [reply circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java]: :) if you have a better message let me know

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java (hunk 3 above)
Comment (ddcprg) [reply circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java]: I've created this method. Is static because it does not access any of the class members

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java (hunk 4 above)
Comment (ddcprg) [reply circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java]: I can inline it, no problem

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/CloseableMetaStoreClientFactory.java (hunk 5 above)
Comment (ddcprg) [reply circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/CloseableMetaStoreClientFactory.java]: this code is mine

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java (hunk 6 above)
Comment (ddcprg) [reply circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java]: this is my code

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java (hunk 7 above)
Comment (ddcprg) [reply circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java]: these were copied from Hive, I'll add a header on each method

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/CloseableMetaStoreClientFactory.java (hunk 5 above)
Comment (massdosage) [reply circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/CloseableMetaStoreClientFactory.java]: OK, loving the performance enhancing ++i as opposed to i++ ;p

File: circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java (hunk 3 above)
Comment (massdosage) [reply circus-train-api/src/main/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12x.java]: OK, we typically only make things static if they need to be, NABD either way here.

File: circus-train-api/src/test/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12xTest.java [hunk 8]
```diff
@@ -0,0 +1,152 @@
...
+    private final ThriftHiveMetastore.Client delegate;
+
+    public RelaxedTServiceClient(ThriftHiveMetastore.Client delegate) {
+      super(delegate.getInputProtocol());
+      this.delegate = delegate;
+    }
+
+    @Override
+    public GetTableResult get_table_req(GetTableRequest req) throws MetaException, NoSuchObjectException, TException {
+      // Safeguard: this method should not be invoked since we are testing directrly calling the compatibility class
```
Comment (massdosage) [inline circus-train-api/src/test/java/com/hotels/bdp/circustrain/api/metastore/compatibility/HiveMetaStoreClientCompatibility12xTest.java]: directrly -> directly

**Comment by ddcprg** [comment]
I missed an entry in CHANGELOG, I'll add it and then do a release today
